# Site settings
title: The Deeds of a Man in His Prime
subtitle: Badhiya hai
description: > # this means to ignore newlines until "baseurl:"
    Old writings from the yesteryears, almost lost to the sands of time
    but recovered by the mystical powers of Jekyll, now served without restraint.
baseurl: ""
url: "http://old.pratul.in"

# Build settings
markdown: kramdown
